spring.application.name=smart-park

spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

spring.datasource.url=jdbc:h2:mem:smart-park;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:password}

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jackson.property-naming-strategy=SNAKE_CASE

logging.level.root=ERROR