CREATE TABLE parking_lots
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    lot_id     VARCHAR(255)                            NOT NULL,
    location   VARCHAR(255)                            NOT NULL,
    capacity   INT DEFAULT 0                           NOT NULL,
    CONSTRAINT pk_parking_lots PRIMARY KEY (id)
);

CREATE TABLE parking_transactions
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    parking_lot_id        VARCHAR(255)                            NOT NULL,
    vehicle_license_plate VARCHAR(255)                            NOT NULL,
    parking_status        VARCHAR(255),
    CONSTRAINT pk_parking_transactions PRIMARY KEY (id)
);

CREATE TABLE vehicles
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    license_plate VARCHAR(255)                            NOT NULL,
    vehicle_type  VARCHAR(255),
    owner_name    VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_vehicles PRIMARY KEY (id)
);

ALTER TABLE parking_lots
    ADD CONSTRAINT uc_parking_lots_lotid UNIQUE (lot_id);

ALTER TABLE vehicles
    ADD CONSTRAINT uc_vehicles_licenseplate UNIQUE (license_plate);